name: azure_application_insights
description: A Dart client to integrate with Azure's Application Insights service
version: 3.1.0
repository: https://github.com/kentcb/azure_application_insights

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  crypto: ^3.0.0
  http: ^0.13.0
  logging: ^1.0.2
  meta: ^1.3.0
  stack_trace: ^1.10.0

dev_dependencies:
  build_runner: ^2.1.10
  lint: ^1.8.2
  mockito: ^5.1.0
  quiver: ^3.0.0
  test: ^1.21.0
