name: azure_application_insights
description: A Dart client to integrate with Azure's Application Insights service
version: 4.0.0
repository: https://github.com/kentcb/azure_application_insights

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  crypto: ^3.0.0
  http: '>=0.13.6 <2.0.0'
  logging: ^1.2.0
  meta: ^1.9.1
  stack_trace: ^1.11.1

dev_dependencies:
  build_runner: ^2.4.6
  lint: ^2.1.2
  mockito: ^5.4.2
  quiver: ^3.2.1
  test: ^1.24.4